#!/usr/bin/env sh
#
# Run all tests in batches to avoid overloading docker-in-docker with podman.

error() {
    echo "$0: ERROR: $*" >&2
    exit 1
}

features="$(find src -maxdepth 1 -mindepth 1 -printf '%f ')"
images="mcr.microsoft.com/devcontainers/base:debian mcr.microsoft.com/devcontainers/base:ubuntu mcr.microsoft.com/devcontainers/base:alpine registry.fedoraproject.org/fedora:latest registry.access.redhat.com/ubi9/ubi:latest"

devcontainer features test --global-scenarios-only || \
    error "Global scenarios failed: exit code: $?"

for feature in ${features}; do
    for image in ${images}; do
        devcontainer features test --skip-scenarios --features "${feature}" --base-image "${image}" || \
            error "Autogenerated tests for ${feature} on ${image} failed: exit code: $?"
    done
    devcontainer features test --skip-autogenerated --skip-duplicated --features "${feature}" || \
        error "Scenario tests for ${feature} failed: exit code: $?"
done
