#!/usr/bin/env bash
set -e

if [ -x /bin/busybox ]; then
    # shellcheck disable=SC1091
    . alpine-features-test-lib.sh
else
    # shellcheck disable=SC1091
    source dev-container-features-test-lib
fi

# Autogenerated tests will not install any tools
check "Verify a version of packer is not installed" test ! -f /usr/bin/local/packer -a ! -f /usr/bin/packer
check "Verify a version of terraform is not installed" test ! -f /usr/bin/local/terraform -a ! -f /usr/bin/terraform
check "Verify a version of vault is not installed" test ! -f /usr/bin/local/vault -a ! -f /usr/bin/vault
reportResults
