# Use release-please to manage changelogs and versioning but with final tagging and releasing disabled in config. Those
# steps will still be handled by the devcontainer release workflow.
# spell-checker: disable
---
name: release-please

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        uses: GoogleCloudPlatform/release-please-action@v4.1.3
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
