---
name: "CI - Test Features"
# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      features: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v6
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            buf:
              - 'src/buf/install.sh'
              - 'test/buf/**'
            direnv:
              - 'src/direnv/install.sh'
              - 'test/direnv/**'
            flux:
              - 'src/flux/install.sh'
              - 'test/flux/**'
            gcrane:
              - 'src/gcrane/install.sh'
              - 'test/gcrane/**'
            google-cloud-cli:
              - 'src/google-cloud-cli/install.sh'
              - 'test/google-cloud-cli/**'
            golangci-lint:
              - 'src/golangci-lint/install.sh'
              - 'test/golangci-lint/**'
            goreleaser:
              - 'src/goreleaser/install.sh'
              - 'test/goreleaser/**'
            hashicorp:
              - 'src/hashicorp/install.sh'
              - 'test/hashicorp/**'
            hadolint:
              - 'src/hadolint/install.sh'
              - 'test/hadolint/**'
            opentofu:
              - 'src/opentofu/install.sh'
              - 'test/opentofu/**'
            sops:
              - 'src/sops/install.sh'
              - 'test/sops/**'
            starship:
              - 'src/starship/install.sh'
              - 'test/starship/**'
            talisman:
              - 'src/talisman/install.sh'
              - 'test/talisman/**'
            terraform-docs:
              - 'src/terraform-docs/install.sh'
              - 'test/terraform-docs/**'
            terragrunt:
              - 'src/terragrunt/install.sh'
              - 'test/terragrunt/**'
            tflint:
              - 'src/tflint/install.sh'
              - 'test/tflint/**'
            vesctl:
              - 'src/vesctl/install.sh'
              - 'test/vesctl/**'

  test-autogenerated:
    needs: changes
    if: ${{ needs.changes.outputs.features != '[]' }}
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
      contents: read
    strategy:
      matrix:
        features: ${{ fromJSON(needs.changes.outputs.features) }}
        baseImage:
          - mcr.microsoft.com/devcontainers/base:alpine
          - mcr.microsoft.com/devcontainers/base:debian
          - mcr.microsoft.com/devcontainers/base:ubuntu
          - registry.fedoraproject.org/fedora:latest
          - registry.access.redhat.com/ubi9/ubi:latest
    steps:
      - uses: actions/checkout@v6

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Generating tests for '${{ matrix.features }}' against '${{ matrix.baseImage }}'"
        run: devcontainer features test --skip-scenarios -f ${{ matrix.features }} -i ${{ matrix.baseImage }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test-scenarios:
    needs: changes
    if: ${{ needs.changes.outputs.features != '[]' }}
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
      contents: read
    strategy:
      matrix:
        features: ${{ fromJSON(needs.changes.outputs.features) }}
    steps:
      - uses: actions/checkout@v6

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Generating tests for '${{ matrix.features }}' scenarios"
        run: devcontainer features test -f ${{ matrix.features }} --skip-autogenerated --skip-duplicated
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test-global:
    needs: changes
    if: ${{ needs.changes.outputs.features != '[]' }}
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Testing global scenarios"
        run: devcontainer features test --global-scenarios-only
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
