---
name: "CI - Test Features"
# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      features: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            buf:
              - 'src/buf/**'
              - 'test/buf/**'
            direnv:
              - 'src/direnv/**'
              - 'test/direnv/**'
            google-cloud-cli:
              - 'src/google-cloud-cli/**'
              - 'test/google-cloud-cli/**'
            goreleaser:
              - 'src/goreleaser/**'
              - 'test/goreleaser/**'
            hashicorp:
              - 'src/hashicorp/**'
              - 'test/hashicorp/**'
            opentofu:
              - 'src/opentofu/**'
              - 'test/opentofu/**'
            starship:
              - 'src/starship/**'
              - 'test/starship/**'
            talisman:
              - 'src/talisman/**'
              - 'test/talisman/**'
            terraform-docs:
              - 'src/terraform-docs/**'
              - 'test/terraform-docs/**'
            terragrunt:
              - 'src/terragrunt/**'
              - 'test/terragrunt/**'
            tflint:
              - 'src/tflint/**'
              - 'test/tflint/**'

  test-autogenerated:
    needs: changes
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        features: ${{ fromJSON(needs.changes.outputs.features) }}
        baseImage:
          - mcr.microsoft.com/devcontainers/base:alpine
          - mcr.microsoft.com/devcontainers/base:debian
          - mcr.microsoft.com/devcontainers/base:ubuntu
          - registry.fedoraproject.org/fedora:latest
          - registry.access.redhat.com/ubi9/ubi:latest
    steps:
      - uses: actions/checkout@v4

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Generating tests for '${{ matrix.features }}' against '${{ matrix.baseImage }}'"
        run: devcontainer features test --skip-scenarios -f ${{ matrix.features }} -i ${{ matrix.baseImage }}

  test-scenarios:
    needs: changes
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        features: ${{ fromJSON(needs.changes.outputs.features) }}
    steps:
      - uses: actions/checkout@v4

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Generating tests for '${{ matrix.features }}' scenarios"
        run: devcontainer features test -f ${{ matrix.features }} --skip-autogenerated --skip-duplicated

  test-global:
    needs: changes
    if: ${{ needs.changes.outputs.features != '[]' }}
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Testing global scenarios"
        run: devcontainer features test --global-scenarios-only
