---
name: "Validate devcontainer-feature.json files"
# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features:
          - buf
          - flux
          - gcrane
          - google-cloud-cli
          - goreleaser
          - grpcurl
          - hadolint
          - hashicorp
          - talisman
          - tflint
          - vesctl
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Install latest devcontainer CLI
        run: npm install -g @devcontainers/cli
      - name: Validate devcontainer-feature.json files
        run: |
            devcontainer features package -f --log-level info ./src/${{ matrix.features }}
